import bcrypt from 'bcryptjs';

/**
 * seedExtended.js
 * Ensures EVERY category and EVERY city has verified NGOs and active opportunities,
 * and sets up realistic completed volunteer hours across college squads for the leaderboard.
 */

export function seedExtendedData(db) {
  const hash = bcrypt.hashSync('password123', 10);

  // 1. Ensure all 10 cities are registered in the cities table
  const allCities = [
    'Chennai',
    'Bengaluru',
    'Hyderabad',
    'Mumbai',
    'Delhi',
    'Pune',
    'Kolkata',
    'Ahmedabad',
    'Coimbatore',
    'Vellore'
  ];

  const insertCity = db.prepare(`
    INSERT OR IGNORE INTO cities (id, name, is_active)
    VALUES (?, ?, 1)
  `);
  allCities.forEach((city, idx) => {
    insertCity.run(`city_ext_${idx + 1}`, city);
  });

  // 2. Ensure prominent local colleges exist for each city
  const extendedColleges = [
    { name: 'SRM Kattankulathur (KTR)', category: 'SRM', city: 'Chennai' },
    { name: 'IIT Madras', category: 'IIT', city: 'Chennai' },
    { name: 'Anna University', category: 'UNIVERSITY', city: 'Chennai' },
    { name: 'VIT Vellore', category: 'VIT', city: 'Vellore' },
    { name: 'VIT Chennai', category: 'VIT', city: 'Chennai' },
    { name: 'University of Delhi', category: 'UNIVERSITY', city: 'Delhi' },
    { name: 'IIT Delhi', category: 'IIT', city: 'Delhi' },
    { name: 'IIT Bombay', category: 'IIT', city: 'Mumbai' },
    { name: 'St. Xavier\'s College Mumbai', category: 'UNIVERSITY', city: 'Mumbai' },
    { name: 'IISc / RV College Bengaluru', category: 'UNIVERSITY', city: 'Bengaluru' },
    { name: 'IIT Hyderabad', category: 'IIT', city: 'Hyderabad' },
    { name: 'Osmania University', category: 'UNIVERSITY', city: 'Hyderabad' },
    { name: 'COEP Technological University', category: 'UNIVERSITY', city: 'Pune' },
    { name: 'Symbiosis International University', category: 'UNIVERSITY', city: 'Pune' },
    { name: 'Jadavpur University', category: 'UNIVERSITY', city: 'Kolkata' },
    { name: 'Presidency University Kolkata', category: 'UNIVERSITY', city: 'Kolkata' },
    { name: 'IIT Gandhinagar', category: 'IIT', city: 'Ahmedabad' },
    { name: 'Gujarat University', category: 'UNIVERSITY', city: 'Ahmedabad' },
    { name: 'PSG College of Technology', category: 'UNIVERSITY', city: 'Coimbatore' },
    { name: 'Amrita Vishwa Vidyapeetham', category: 'UNIVERSITY', city: 'Coimbatore' }
  ];

  const insertCollege = db.prepare(`
    INSERT OR IGNORE INTO colleges (id, name, category, city, is_active)
    VALUES (?, ?, ?, ?, 1)
  `);
  extendedColleges.forEach((c, idx) => {
    insertCollege.run(`col_ext_${idx + 100}`, c.name, c.category, c.city);
  });

  // 3. Verified NGOs across ALL 10 Cities and ALL Categories
  const organizationsToSeed = [
    // --- CHENNAI ---
    {
      id: 'org_srm_outreach',
      name: 'SRM Community Action & Outreach Cell',
      email: 'outreach@srmist.edu.in',
      orgName: 'SRM Community Action & Outreach Cell',
      city: 'Chennai',
      role: 'Outreach Director',
      focus: 'Education, Healthcare, Community Action',
      bio: 'Central community engagement wing of SRMIST connecting student cohorts with public services.',
      status: 'govt_registered',
      darpan: 'TN/2018/0201948',
      regNum: 'SRM-UGC-ACT-2002',
      regType: 'University Statutory Outreach Wing',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Dr. C. Muthamizhchelvan',
      score: 98,
      notes: 'Statutory Outreach Wing of SRMIST recognized by UGC and Ministry of Education.'
    },
    {
      id: 'org_paws_animal',
      name: 'Blue Cross & Paws Shelter Foundation',
      email: 'shelter@bluecrosspaws.org',
      orgName: 'Blue Cross & Paws Animal Care Trust',
      city: 'Chennai',
      role: 'Shelter Coordinator',
      focus: 'Animal Welfare, Rescue & Rehabilitation, Vaccine Drives',
      bio: 'AWBI-recognized sanctuary providing emergency animal care, feeding drives, and rescue.',
      status: 'verified',
      darpan: 'TN/2015/0074219',
      regNum: 'TN-AWBI-2015-3810',
      regType: 'Animal Welfare Charitable Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Dr. S. Chinny Krishna',
      score: 97,
      notes: 'Recognized by Animal Welfare Board of India (AWBI).'
    },
    {
      id: 'org_cleancity',
      name: 'CleanCity Urban Trust',
      email: 'info@cleancity.org',
      orgName: 'CleanCity Urban Trust',
      city: 'Chennai',
      role: 'Trustee & Coastal Lead',
      focus: 'Environment, Coastal Conservation, Marine Waste Audit',
      bio: 'Mobilizing citizens and university students along the coastline for marine waste diversion.',
      status: 'verified',
      darpan: 'TN/2017/0158291',
      regNum: 'TN-SOC-2017-0492',
      regType: 'Registered Environmental Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Kavita Merchant',
      score: 94,
      notes: 'Audited coastal marine ecology trust.'
    },
    {
      id: 'org_chennai_civic',
      name: 'Chennai Youth Civic & Electoral Forum',
      email: 'civic@chennaiyouth.org',
      orgName: 'Chennai Youth Civic & Democratic Trust',
      city: 'Chennai',
      role: 'Campaign Director',
      focus: 'Civic & Democracy, Voter Literacy, Citizen Rights',
      bio: 'Youth-led democratic forum mobilizing students across colleges for 100% electoral participation.',
      status: 'govt_registered',
      darpan: 'TN/2019/0149201',
      regNum: 'TN-SOC-2019-3391',
      regType: 'Registered Electoral Literacy Society',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'R. Soundararajan',
      score: 93,
      notes: 'Empanelled with Tamil Nadu Chief Electoral Officer Youth Club guidelines.'
    },

    // --- BENGALURU ---
    {
      id: 'org_teachall',
      name: 'TeachAll Youth Initiative',
      email: 'coordinator@teachall.org',
      orgName: 'TeachAll Youth Initiative',
      city: 'Bengaluru',
      role: 'Education Director',
      focus: 'Education, STEM Mentorship, Digital Literacy',
      bio: 'Enabling collegiate volunteers to run interactive coding and science experiments for rural schools.',
      status: 'verified',
      darpan: 'KA/2019/0082716',
      regNum: 'U85300KA2019NPL128490',
      regType: 'Section 8 Non-Profit Company',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Radhika Ramaswamy',
      score: 95,
      notes: 'MCA Section 8 Non-Profit with audited financial transparency.'
    },
    {
      id: 'org_blr_animal',
      name: 'CUPA Compassion Animal Welfare Trust',
      email: 'care@cupabangalore.org',
      orgName: 'Compassion Unlimited Plus Action (CUPA)',
      city: 'Bengaluru',
      role: 'Sanctuary Manager',
      focus: 'Animal Welfare, Trauma Care, Foster & Adoption',
      bio: 'Pioneering animal welfare organization running veterinary clinics, adoption, and street dog care.',
      status: 'verified',
      darpan: 'KA/2016/0104829',
      regNum: 'KA-TR-2016-1192',
      regType: 'Registered Animal Trust (AWBI)',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Crystal Rogers / Suparna Ganguly',
      score: 96,
      notes: 'Full AWBI accreditation and 80G tax exemption.'
    },
    {
      id: 'org_blr_env',
      name: 'Bangalore Lake & Urban Ecology Guardians',
      email: 'lakes@blreco.org',
      orgName: 'Bangalore Eco Regeneration Trust',
      city: 'Bengaluru',
      role: 'Wetland Lead',
      focus: 'Environment, Lake Rejuvenation, Water Testing',
      bio: 'Dedicated to restoring Bellandur, Varthur, and Kaikondrahalli micro-wetlands with citizen science.',
      status: 'verified',
      darpan: 'KA/2018/0091823',
      regNum: 'KA-SOC-2018-7712',
      regType: 'Registered Trust',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Anand Malligawad',
      score: 94,
      notes: 'Recognized for reviving 20+ urban lakes in Bengaluru.'
    },
    {
      id: 'org_blr_civic',
      name: 'Janaagraha Collegiate Civic League',
      email: 'squads@janaagraha.org',
      orgName: 'Janaagraha Centre for Citizenship & Democracy',
      city: 'Bengaluru',
      role: 'Youth Programs Head',
      focus: 'Civic & Democracy, Ward Governance, Voter Enrolment',
      bio: 'Transforming quality of life in cities through student civic participation and democratic accountability.',
      status: 'verified',
      darpan: 'KA/2014/0048192',
      regNum: 'KA-SOC-2014-9912',
      regType: 'Public Charitable Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Ramesh Ramanathan',
      score: 99,
      notes: 'Leading national think-tank for urban governance and civic education.'
    },
    {
      id: 'org_blr_health',
      name: 'Samarthya Health & Wellness Mission',
      email: 'outreach@samarthyahealth.org',
      orgName: 'Samarthya Community Health Trust',
      city: 'Bengaluru',
      role: 'Field Coordinator',
      focus: 'Healthcare, Blood Donation, Preventive Medicine',
      bio: 'Running free diagnostics and primary health awareness in peri-urban tech corridors.',
      status: 'verified',
      darpan: 'KA/2020/0173819',
      regNum: 'KA-SOC-2020-4102',
      regType: 'Registered Medical Society',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Dr. Vivek Jawali',
      score: 93,
      notes: 'Regular mobile clinics for construction worker families.'
    },

    // --- HYDERABAD ---
    {
      id: 'org_youthforseva',
      name: 'Youth For Seva Hyderabad',
      email: 'contact@youthforseva.org',
      orgName: 'Youth For Seva Fellowship',
      city: 'Hyderabad',
      role: 'State Coordinator',
      focus: 'Education, Community Action, Library Drives',
      bio: 'Collegiate volunteering movement bridging campus youth with social organizations across Telangana.',
      status: 'verified',
      darpan: 'TS/2018/0173820',
      regNum: 'TS-SOC-2018-9921',
      regType: 'Registered Society',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Venkatesh Murthy',
      score: 96,
      notes: 'Empanelled with Telangana State Youth Development.'
    },
    {
      id: 'org_hyd_animal',
      name: 'Blue Cross Hyderabad Sanctuary',
      email: 'rescue@bluecrosshyd.org',
      orgName: 'Blue Cross of Hyderabad Charitable Trust',
      city: 'Hyderabad',
      role: 'Shelter Director',
      focus: 'Animal Welfare, Rescue, ABC & Anti-Rabies',
      bio: 'AWBI certified shelter caring for 1,000+ injured animals in Jubilee Hills and Old City.',
      status: 'verified',
      darpan: 'TS/2015/0068192',
      regNum: 'TS-AWBI-2015-4410',
      regType: 'Registered Animal Welfare Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Amala Akkineni',
      score: 98,
      notes: 'Over 30 years of humane animal treatment in Hyderabad.'
    },
    {
      id: 'org_hyd_env',
      name: 'Musi River Clean Eco Foundation',
      email: 'savemusi@ecohyd.org',
      orgName: 'Musi & Osman Sagar Ecological Foundation',
      city: 'Hyderabad',
      role: 'River Basin Lead',
      focus: 'Environment, River Cleanup, Urban Forests',
      bio: 'Restoring historical waterways and lakes of the Deccan plateau through student weekend drives.',
      status: 'verified',
      darpan: 'TS/2019/0128491',
      regNum: 'TS-SOC-2019-5821',
      regType: 'Registered Environmental Society',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'K. Purushotham',
      score: 92,
      notes: 'Active participant in Telangana Haritha Haram.'
    },
    {
      id: 'org_hyd_civic',
      name: 'Telangana Democratic Literacy League',
      email: 'vote@telanganacivic.org',
      orgName: 'Telangana Youth Civic League',
      city: 'Hyderabad',
      role: 'Electoral Coordinator',
      focus: 'Civic & Democracy, Youth Voting, Public RTI',
      bio: 'Promoting informed civic leadership and voter enrolment in colleges across Telangana.',
      status: 'govt_registered',
      darpan: 'TS/2021/0198421',
      regNum: 'TS-TR-2021-3912',
      regType: 'Registered Educational Trust',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Prof. Haragopal',
      score: 91,
      notes: 'Conducting campus voter registration drives.'
    },

    // --- MUMBAI ---
    {
      id: 'org_mumbai_animal',
      name: 'The Welfare of Stray Dogs (WSD Mumbai)',
      email: 'wsd@wsdmumbai.org',
      orgName: 'The Welfare of Stray Dogs Trust',
      city: 'Mumbai',
      role: 'Outreach Manager',
      focus: 'Animal Welfare, Street Dog Care, Anti-Rabies',
      bio: 'Leading Mumbai animal NGO carrying out sterilization, health camps, and adoption drives.',
      status: 'verified',
      darpan: 'MH/2015/0082711',
      regNum: 'MH-AWBI-2015-8812',
      regType: 'Charitable Trust (AWBI)',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Abodh Aras',
      score: 97,
      notes: 'Recipient of national animal welfare excellence awards.'
    },
    {
      id: 'org_mumbai_edu',
      name: 'Pratham Mumbai Youth Learning Cell',
      email: 'volunteer@prathammumbai.org',
      orgName: 'Pratham Education Foundation Mumbai',
      city: 'Mumbai',
      role: 'Volunteer Coordinator',
      focus: 'Education, Remedial Teaching, Library Drives',
      bio: 'Every child in school and learning well. Engaging college students for foundational reading.',
      status: 'verified',
      darpan: 'MH/2014/0051928',
      regNum: 'BOM-SOC-1994-1182',
      regType: 'Registered Educational Society',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Dr. Rukmini Banerji',
      score: 99,
      notes: 'Publisher of the Annual Status of Education Report (ASER).'
    },
    {
      id: 'org_mumbai_civic',
      name: 'Praja Civic Action Fellowship',
      email: 'youth@praja.org',
      orgName: 'Praja Foundation Mumbai',
      city: 'Mumbai',
      role: 'Civic Engagement Lead',
      focus: 'Civic & Democracy, Municipal Governance, Citizen Audits',
      bio: 'Enabling citizen participation in city governance through data-driven advocacy and youth fellowship.',
      status: 'verified',
      darpan: 'MH/2016/0091823',
      regNum: 'MH-TR-2016-3391',
      regType: 'Public Charitable Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Nitai Mehta',
      score: 98,
      notes: 'Publishes annual whitepapers on civic performance in BMC wards.'
    },
    {
      id: 'org_mumbai_health',
      name: 'Niramaya Arogya Seva Mumbai',
      email: 'clinic@niramayamumbai.org',
      orgName: 'Niramaya Health Foundation',
      city: 'Mumbai',
      role: 'Medical Camp Lead',
      focus: 'Healthcare, Child Nutrition, Maternal Wellness',
      bio: 'Delivering holistic healthcare solutions in informal slum settlements in Dharavi and Govandi.',
      status: 'verified',
      darpan: 'MH/2017/0129481',
      regNum: 'MH-SOC-2017-7718',
      regType: 'Registered Health Trust',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Dr. Anita Joshi',
      score: 94,
      notes: 'Operates 12 urban primary health clinics.'
    },

    // --- DELHI ---
    {
      id: 'org_greenearth',
      name: 'GreenEarth India Foundation',
      email: 'contact@greenearth.org',
      orgName: 'GreenEarth India Foundation',
      city: 'Delhi',
      role: 'Programs Lead',
      focus: 'Environment, Afforestation, Biodiversity, Yamuna River',
      bio: 'National non-profit coordinating civic tree planting, Yamuna bank cleanup, and urban biodiversity.',
      status: 'verified',
      darpan: 'DL/2016/0114829',
      regNum: 'DEL-TR-2016-8819',
      regType: 'Registered Public Environmental Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Dr. Sunita Narain / Aniket Mathur',
      score: 96,
      notes: 'NITI Aayog Darpan registered with 80G tax exemption.'
    },
    {
      id: 'org_civic_democracy',
      name: 'Civic Voice & Democracy Youth Mission',
      email: 'vote@civicvoice.org',
      orgName: 'Civic Voice & Youth Democracy Initiative',
      city: 'Delhi',
      role: 'National Campaign Lead',
      focus: 'Civic & Democracy, Voter Literacy, Youth Electoral Enrolment',
      bio: 'Non-partisan civil society foundation mobilizing student communities for 100% democratic turnout.',
      status: 'govt_registered',
      darpan: 'DL/2014/0059124',
      regNum: 'DEL-SOC-2014-4412',
      regType: 'Registered Electoral Literacy Trust',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Prof. Jagdeep Chhokar',
      score: 99,
      notes: 'Empanelled with National Election Literacy Club (ELC) guidelines.'
    },
    {
      id: 'org_delhi_animal',
      name: 'Friendicoes SECA Animal Shelter',
      email: 'rescue@friendicoes.org',
      orgName: 'Friendicoes Society for Eradication of Cruelty',
      city: 'Delhi',
      role: 'Shelter Lead',
      focus: 'Animal Welfare, Hospital, 24/7 Ambulance, Adoption',
      bio: 'One of India\'s oldest animal shelters under Defense Colony flyover, caring for horses, dogs, cats.',
      status: 'verified',
      darpan: 'DL/2015/0048192',
      regNum: 'DL-SOC-1979-0912',
      regType: 'Registered Animal Welfare Society',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Geeta Seshamani',
      score: 98,
      notes: 'Operating since 1979 with over 150 permanent animal residents.'
    },
    {
      id: 'org_delhi_edu',
      name: 'Katha Children\'s Literacy Project',
      email: 'books@katha.org',
      orgName: 'Katha Educational Trust',
      city: 'Delhi',
      role: 'Learning Center Coordinator',
      focus: 'Education, Storytelling, Slum Reading Labs',
      bio: 'Igniting curiosity and reading joy in children living in Govindpuri and Okhla slum clusters.',
      status: 'verified',
      darpan: 'DL/2015/0071829',
      regNum: 'DL-TR-1988-1920',
      regType: 'Registered Educational Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Geeta Dharmarajan',
      score: 97,
      notes: 'Padma Shri recognized literary innovation non-profit.'
    },
    {
      id: 'org_delhi_health',
      name: 'Goonj Urban Health & Dignity Drive',
      email: 'mail@goonj.org',
      orgName: 'Goonj Foundation',
      city: 'Delhi',
      role: 'Relief Coordinator',
      focus: 'Healthcare, Menstrual Hygiene, Disaster Relief',
      bio: 'Turning urban surplus into rural development and dignity across 27 Indian states.',
      status: 'verified',
      darpan: 'DL/2014/0038192',
      regNum: 'DL-SOC-1999-4419',
      regType: 'Registered Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Anshu Gupta',
      score: 99,
      notes: 'Ramon Magsaysay Award-winning organization.'
    },

    // --- PUNE ---
    {
      id: 'org_pune_swach',
      name: 'SWaCH & Waste Warriors Pune',
      email: 'contact@swachcoop.org',
      orgName: 'SWaCH Seva Cooperative & Trust',
      city: 'Pune',
      role: 'Operations Coordinator',
      focus: 'Environment, Solid Waste Segregation, Eco-Sanitation',
      bio: 'India\'s first wholly-owned waste picker cooperative working with Pune Municipal Corporation.',
      status: 'verified',
      darpan: 'MH/2017/0138291',
      regNum: 'PUN-SOC-2017-9102',
      regType: 'Cooperative Society & Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Laxmi Narayan',
      score: 96,
      notes: 'Partnered with PMC for 100% door-to-door waste diversion.'
    },
    {
      id: 'org_pune_animal',
      name: 'RESQ Wildlife & Animal Charitable Trust Pune',
      email: 'rescue@resqct.org',
      orgName: 'RESQ Charitable Trust Pune',
      city: 'Pune',
      role: 'Sanctuary Director',
      focus: 'Animal Welfare, Wildlife Rehab, Stray Dog Rescue',
      bio: 'Operating full-fledged trauma center and wildlife rehabilitation sanctuary in Bavdhan, Pune.',
      status: 'verified',
      darpan: 'MH/2016/0119821',
      regNum: 'PUN-AWBI-2016-5510',
      regType: 'Animal Welfare Charitable Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Neha Panchamiya',
      score: 97,
      notes: 'State-of-the-art wildlife trauma center recognized by Maharashtra Forest Dept.'
    },
    {
      id: 'org_pune_edu',
      name: 'Deepstambha Pune Youth Mentorship',
      email: 'mentor@deepstambha.org',
      orgName: 'Deepstambha Charitable Foundation',
      city: 'Pune',
      role: 'Youth Program Head',
      focus: 'Education, Career Mentorship, Rural Student Guidance',
      bio: 'Empowering marginalized rural and tribal students studying in Pune colleges with career skills.',
      status: 'verified',
      darpan: 'MH/2018/0149201',
      regNum: 'PUN-SOC-2018-8812',
      regType: 'Registered Educational Society',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Yajurvendra Mahajan',
      score: 95,
      notes: 'Special emphasis on differently-abled and tribal youth.'
    },
    {
      id: 'org_pune_civic',
      name: 'Pune Citizen Democracy Forum',
      email: 'citizen@punecivic.org',
      orgName: 'Pune Citizen & Youth Forum',
      city: 'Pune',
      role: 'Campaign Lead',
      focus: 'Civic & Democracy, Public Transport Advocacy, Youth Enrolment',
      bio: 'Student-led collective advocating for safe pedestrian walkways and ethical electoral voting.',
      status: 'govt_registered',
      darpan: 'MH/2019/0173819',
      regNum: 'PUN-TR-2019-4102',
      regType: 'Public Trust',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Sujit Patwardhan',
      score: 92,
      notes: 'Active since 2005 on sustainable mobility.'
    },
    {
      id: 'org_pune_health',
      name: 'Sanjeevan Arogya Trust Pune',
      email: 'health@sanjeevanpune.org',
      orgName: 'Sanjeevan Health Society',
      city: 'Pune',
      role: 'Medical Director',
      focus: 'Healthcare, Mobile Clinics, Geriatric Support',
      bio: 'Conducting community health checkups and elder wellness camps in Katraj and Hadapsar.',
      status: 'verified',
      darpan: 'MH/2019/0182710',
      regNum: 'PUN-SOC-2019-1102',
      regType: 'Charitable Health Society',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Dr. Dhananjay Kelkar',
      score: 93,
      notes: 'Serving 50,000+ suburban residents every year.'
    },

    // --- KOLKATA ---
    {
      id: 'org_kolkata_env',
      name: 'Sundarbans & Hooghly Eco Alliance',
      email: 'conserve@sundarbancoast.org',
      orgName: 'Hooghly & Sundarban Delta Conservation Trust',
      city: 'Kolkata',
      role: 'Mangrove Scientist',
      focus: 'Environment, River Rejuvenation, Mangrove Planting',
      bio: 'Restoring Hooghly river ghats and supporting Sundarbans delta communities with coastal afforestation.',
      status: 'verified',
      darpan: 'WB/2017/0129481',
      regNum: 'WB-SOC-2017-8819',
      regType: 'Registered Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Dr. Pranabesh Sanyal',
      score: 95,
      notes: 'Partnered with Sundarban Biosphere Reserve.'
    },
    {
      id: 'org_kolkata_animal',
      name: 'Calcutta Animal Rescue & Care Trust',
      email: 'rescue@calcuttaanimal.org',
      orgName: 'Calcutta Animal Rescue & Care Trust',
      city: 'Kolkata',
      role: 'Veterinary Coordinator',
      focus: 'Animal Welfare, Street Animal Vaccination, Equine Care',
      bio: 'Running veterinary ambulances, emergency treatment, and horse welfare around Maidan Kolkata.',
      status: 'verified',
      darpan: 'WB/2016/0091823',
      regNum: 'WB-AWBI-2016-4412',
      regType: 'Animal Welfare Trust (AWBI)',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Debasis Chakrabarti',
      score: 94,
      notes: 'Active emergency animal trauma team in South Kolkata.'
    },
    {
      id: 'org_kolkata_edu',
      name: 'Bikash Youth Literacy Mission Kolkata',
      email: 'education@bikashkolkata.org',
      orgName: 'Bikash Educational Society Kolkata',
      city: 'Kolkata',
      role: 'Learning Director',
      focus: 'Education, Evening Schools, Digital Coding',
      bio: 'Running 15 community learning centers along railway sidings in Sealdah and Howrah.',
      status: 'verified',
      darpan: 'WB/2018/0149201',
      regNum: 'WB-SOC-2018-3312',
      regType: 'Registered Society',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Shubhashis Ghosh',
      score: 93,
      notes: 'Mobilizing college student tutors across Kolkata universities.'
    },
    {
      id: 'org_kolkata_health',
      name: 'Calcutta Rescue Foundation',
      email: 'info@calcuttarescue.org',
      orgName: 'Calcutta Rescue Foundation',
      city: 'Kolkata',
      role: 'Clinic Supervisor',
      focus: 'Healthcare, Tuberculosis Treatment, Clean Drinking Water',
      bio: 'Providing free health care, education, and arsenic-safe water to the poorest communities in West Bengal.',
      status: 'verified',
      darpan: 'WB/2014/0051928',
      regNum: 'WB-TR-1991-0021',
      regType: 'Charitable Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Dr. Jack Preger / Jaydeep Chakraborty',
      score: 98,
      notes: 'Legendary grassroots healthcare institution operating four clinics in Kolkata.'
    },
    {
      id: 'org_kolkata_civic',
      name: 'Bengal Citizen Assembly & Democratic Trust',
      email: 'democracy@bengalcivic.org',
      orgName: 'Bengal Citizen Democratic Trust',
      city: 'Kolkata',
      role: 'Electoral Coordinator',
      focus: 'Civic & Democracy, Voter Literacy, Youth Enrolment',
      bio: 'Conducting non-partisan voter awareness, debates, and town halls across university campuses.',
      status: 'govt_registered',
      darpan: 'WB/2020/0173819',
      regNum: 'WB-SOC-2020-5510',
      regType: 'Registered Society',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Prof. Sabyasachi Basu',
      score: 91,
      notes: 'Recognized for collegiate voter literacy clubs.'
    },

    // --- AHMEDABAD ---
    {
      id: 'org_ahmedabad_env',
      name: 'Sabarmati Green Corridor Trust',
      email: 'green@sabarmatieco.org',
      orgName: 'Sabarmati Ecological Restoration Society',
      city: 'Ahmedabad',
      role: 'River Ecologist',
      focus: 'Environment, Riverbank Tree Planting, Soil Restoration',
      bio: 'Creating urban biodiversity groves along Sabarmati riverfront and western drylands.',
      status: 'verified',
      darpan: 'GJ/2018/0119821',
      regNum: 'AHM-SOC-2018-7712',
      regType: 'Registered Trust',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Kartikeya Sarabhai',
      score: 96,
      notes: 'Affiliated with Centre for Environment Education (CEE).'
    },
    {
      id: 'org_ahmedabad_animal',
      name: 'Jivdaya Charitable Trust Ahmedabad',
      email: 'help@jivdayatrust.org',
      orgName: 'Jivdaya Charitable Trust',
      city: 'Ahmedabad',
      role: 'Hospital Director',
      focus: 'Animal Welfare, Avian Trauma Care, Kite Thread Rescue',
      bio: 'Specialized hospital treating 50,000+ injured birds, stray animals, and wild raptors each year.',
      status: 'verified',
      darpan: 'GJ/2015/0071829',
      regNum: 'AHM-AWBI-2015-3310',
      regType: 'Charitable Trust (AWBI)',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Gira Shah',
      score: 99,
      notes: 'Renowned hospital based inside Ahmedabad Panjrapole campus.'
    },
    {
      id: 'org_ahmedabad_edu',
      name: 'Eklavya Education Foundation Ahmedabad',
      email: 'learn@eklavya.org',
      orgName: 'Eklavya Foundation Gujarat',
      city: 'Ahmedabad',
      role: 'Curriculum Head',
      focus: 'Education, Interactive Science, Tribal Schools',
      bio: 'Inspiring curious minds through experiential science experiments in suburban municipal schools.',
      status: 'verified',
      darpan: 'GJ/2016/0091823',
      regNum: 'GJ-SOC-2016-4412',
      regType: 'Registered Educational Society',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Sunil Handa',
      score: 97,
      notes: 'Founded by IIM Ahmedabad alumni.'
    },
    {
      id: 'org_ahmedabad_civic',
      name: 'Janpath Citizen & Democratic Forum',
      email: 'citizen@janpathgujarat.org',
      orgName: 'Janpath Citizen Action Network',
      city: 'Ahmedabad',
      role: 'State Lead',
      focus: 'Civic & Democracy, Social Audits, Voter Awareness',
      bio: 'Federation of voluntary organisations in Gujarat promoting active citizenship and rights.',
      status: 'verified',
      darpan: 'GJ/2017/0129481',
      regNum: 'AHM-TR-2017-9921',
      regType: 'Registered Public Trust',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Harinesh Pandya',
      score: 94,
      notes: 'Leading training institute for grassroots social audits.'
    },
    {
      id: 'org_ahmedabad_health',
      name: 'SEWA Gramin Health & Nutrition Mission',
      email: 'health@sewagujarat.org',
      orgName: 'SEWA Community Health Trust',
      city: 'Ahmedabad',
      role: 'Outreach Manager',
      focus: 'Healthcare, Community Nutrition, Women\'s Health',
      bio: 'Self-Employed Women’s Association running community health cooperatives and barefoot clinics.',
      status: 'verified',
      darpan: 'GJ/2014/0038192',
      regNum: 'GJ-TR-1972-0012',
      regType: 'Registered Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Rehana Riaz',
      score: 98,
      notes: 'Pioneered by Ela Bhatt for women\'s collective empowerment.'
    },

    // --- COIMBATORE ---
    {
      id: 'org_coimbatore_env',
      name: 'Siruthuli Eco & Water Rejuvenation',
      email: 'water@siruthuli.com',
      orgName: 'Siruthuli Ecological NGO',
      city: 'Coimbatore',
      role: 'Managing Trustee',
      focus: 'Environment, Lake Desilting, Noyyal River, Green Kovai',
      bio: 'Citizens of Coimbatore united to rejuvenate water bodies, plant 10 lakh native trees, and harvest rainwater.',
      status: 'verified',
      darpan: 'TN/2016/0082711',
      regNum: 'CBE-TR-2003-0912',
      regType: 'Public Charitable Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Vanitha Mohan',
      score: 99,
      notes: 'Revived 8 major lakes in Coimbatore basin.'
    },
    {
      id: 'org_coimbatore_animal',
      name: 'Humane Animal Society Coimbatore (HAS)',
      email: 'info@hasindia.org',
      orgName: 'Humane Animal Society Coimbatore',
      city: 'Coimbatore',
      role: 'Shelter Coordinator',
      focus: 'Animal Welfare, ABC Program, Anti-Rabies, Sanctuary',
      bio: 'AWBI recognized sanctuary treating sick, injured and abandoned animals in Coimbatore district.',
      status: 'verified',
      darpan: 'TN/2015/0068192',
      regNum: 'CBE-AWBI-2015-1102',
      regType: 'Registered Trust (AWBI)',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Mini Vasudevan',
      score: 97,
      notes: 'Recipient of Nari Shakti Puraskar from the President of India.'
    },
    {
      id: 'org_coimbatore_edu',
      name: 'Shanti Ashram Youth Empowerment Cell',
      email: 'youth@shantiashram.org',
      orgName: 'Shanti Ashram Charitable Trust',
      city: 'Coimbatore',
      role: 'Fellowship Lead',
      focus: 'Education, Child Development, Youth Leadership',
      bio: 'Gandhian institution empowering village children and collegiate youth in Perur and Pollachi.',
      status: 'verified',
      darpan: 'TN/2017/0114829',
      regNum: 'CBE-SOC-1986-0412',
      regType: 'Registered Trust',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Dr. Kezevino Aram',
      score: 98,
      notes: 'Serving 100+ villages across Tamil Nadu.'
    },
    {
      id: 'org_coimbatore_health',
      name: 'Kovai Rural Mobile Health Mission',
      email: 'clinic@kovaihealth.org',
      orgName: 'Kovai Rural Healthcare Society',
      city: 'Coimbatore',
      role: 'Medical Lead',
      focus: 'Healthcare, Diabetes Screening, Rural Clinics',
      bio: 'Providing free specialty doctor consultations and screening camps in Western Ghats foothill villages.',
      status: 'verified',
      darpan: 'TN/2019/0158291',
      regNum: 'CBE-SOC-2019-3312',
      regType: 'Registered Health Society',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'Dr. R. V. Ramani',
      score: 94,
      notes: 'Partnered with regional medical colleges.'
    },
    {
      id: 'org_coimbatore_civic',
      name: 'Kongu Citizen & Democratic Council',
      email: 'vote@kongucivic.org',
      orgName: 'Kongu Youth Democratic Forum',
      city: 'Coimbatore',
      role: 'Coordinator',
      focus: 'Civic & Democracy, Youth Voting, Local Governance',
      bio: 'Promoting youth civic literacy and village panchayat gram sabha attendance among college youth.',
      status: 'govt_registered',
      darpan: 'TN/2021/0173819',
      regNum: 'CBE-TR-2021-4410',
      regType: 'Public Trust',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'S. Shanmugam',
      score: 92,
      notes: 'Conducts annual youth parliament simulations in colleges.'
    },

    // --- VELLORE ---
    {
      id: 'org_vellore_rural',
      name: 'Vellore Rural Development & Social Cell',
      email: 'rural@velloredevelopment.org',
      orgName: 'Vellore Rural Development Trust',
      city: 'Vellore',
      role: 'Project Director',
      focus: 'Education, Village Livelihoods, Women\'s Empowerment',
      bio: 'Partnering with VIT Vellore student chapters to power night schools and smart classes in Katpadi.',
      status: 'verified',
      darpan: 'TN/2018/0091823',
      regNum: 'VEL-SOC-2018-4412',
      regType: 'Registered Trust',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'G. Viswanathan / M. Selvam',
      score: 96,
      notes: 'Long-standing community partner with Vellore educational institutions.'
    },
    {
      id: 'org_vellore_health',
      name: 'CMC Rural Community Health Unit (RUHSA)',
      email: 'ruhsa@cmcvellore.ac.in',
      orgName: 'CMC Vellore RUHSA Department',
      city: 'Vellore',
      role: 'Outreach Head',
      focus: 'Healthcare, Rural Screening, Pediatric Nutrition',
      bio: 'World-renowned rural health program of Christian Medical College Vellore serving KV Kuppam block.',
      status: 'govt_registered',
      darpan: 'TN/2014/0051928',
      regNum: 'VEL-MED-1977-0012',
      regType: 'Statutory Medical Outreach Wing',
      has80g: 1, has12a: 1, fcra: 1,
      trustee: 'Dr. Rita Isaac / Dr. Vikram Mathews',
      score: 99,
      notes: 'Over 40 years of pioneering comprehensive primary rural healthcare.'
    },
    {
      id: 'org_vellore_env',
      name: 'Palar River Basin Ecosystem Care',
      email: 'palar@ecovellore.org',
      orgName: 'Palar River Environmental Society',
      city: 'Vellore',
      role: 'River Conservationist',
      focus: 'Environment, River Sand Recovery, Afforestation',
      bio: 'Mobilizing students from VIT and engineering colleges to plant native trees and protect Palar riverbed.',
      status: 'verified',
      darpan: 'TN/2019/0129481',
      regNum: 'VEL-SOC-2019-8812',
      regType: 'Registered Society',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'K. Balakrishnan',
      score: 93,
      notes: 'Leading citizen water conservation along the Palar basin.'
    },
    {
      id: 'org_vellore_animal',
      name: 'Vellore Compassion & Animal Shelter',
      email: 'animals@vellorecare.org',
      orgName: 'Vellore Animal Welfare Society',
      city: 'Vellore',
      role: 'Shelter Lead',
      focus: 'Animal Welfare, Rescue, Street Feeding, First Aid',
      bio: 'Caring for stray dogs, cattle, and injured birds in Katpadi and Vellore Fort perimeter.',
      status: 'verified',
      darpan: 'TN/2020/0173819',
      regNum: 'VEL-AWBI-2020-5510',
      regType: 'Charitable Trust (AWBI)',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'P. Ravichandran',
      score: 92,
      notes: 'Regular weekend feeding and vaccination rounds.'
    },
    {
      id: 'org_vellore_civic',
      name: 'Vellore Youth Civic & Electoral Forum',
      email: 'vote@velloreyouth.org',
      orgName: 'Vellore Youth Democracy League',
      city: 'Vellore',
      role: 'Convenor',
      focus: 'Civic & Democracy, Campus Voter Helpdesks, Legal Rights',
      bio: 'Enrolling collegiate students on voter lists and educating first-time voters on ethical balloting.',
      status: 'govt_registered',
      darpan: 'TN/2021/0182710',
      regNum: 'VEL-TR-2021-3312',
      regType: 'Public Trust',
      has80g: 1, has12a: 1, fcra: 0,
      trustee: 'R. Srinivasan',
      score: 91,
      notes: 'Conducting voter enrolment kiosks in Katpadi.'
    }
  ];

  // Insert or update all organizations
  const insertOrg = db.prepare(`
    INSERT OR REPLACE INTO users (
      id, name, email, password_hash, role, organization_name, organization_city,
      organization_role, focus_areas, home_city, bio,
      verification_status, ngo_darpan_id, registration_number, registration_type,
      tax_exemption_80g, tax_exemption_12a, fcra_registered, trustee_name,
      verified_at, verification_notes, trust_score, created_at
    ) VALUES (?, ?, ?, ?, 'organization', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  organizationsToSeed.forEach((org) => {
    insertOrg.run(
      org.id,
      org.name,
      org.email,
      hash,
      org.orgName,
      org.city,
      org.role,
      org.focus,
      org.city,
      org.bio,
      org.status,
      org.darpan,
      org.regNum,
      org.regType,
      org.has80g,
      org.has12a,
      org.fcra,
      org.trustee,
      '2026-06-01T10:00:00.000Z',
      org.notes,
      org.score,
      '2026-07-01T08:00:00.000Z'
    );
  });

  // Dedicated Official Student Guest Profile
  const insertStudent = db.prepare(`
    INSERT OR REPLACE INTO users (
      id, name, email, password_hash, role, college, home_city, course, skills, bio, created_at
    ) VALUES (?, ?, ?, ?, 'student', ?, ?, ?, ?, ?, ?)
  `);

  insertStudent.run(
    'user_guest_student',
    'Aarav Sharma (Guest Student)',
    'guest.student@srmist.edu.in',
    hash,
    'SRM Kattankulathur (KTR)',
    'Chennai',
    'B.Tech Computer Science & Engineering',
    'Environmental Action, STEM Mentorship, Animal Care, Digital Literacy, First Aid',
    'Official Student Guest profile for exploring collegiate squads, geofenced QR check-ins, and verified impact credentials.',
    '2026-08-01T08:00:00.000Z'
  );

  // 4. Opportunities across ALL 10 Cities and Categories
  const opportunitiesToSeed = [
    // --- PUNE OPPORTUNITIES ---
    {
      id: 'opp_pune_swach_waste',
      orgId: 'org_pune_swach',
      title: 'SWaCH Zero-Waste Ward Audit & Composting Drive',
      description: 'Join SWaCH waste pickers and environmental mentors to audit dry and wet waste segregation in Kothrud and Deccan. Student squads educate shopkeepers, map plastic waste density, and set up decentralized compost pits.',
      skills: 'Environmental Action, Logistics, Surveying, Community Mobilization',
      city: 'Pune',
      address: 'Deccan Gymkhana & Kothrud Ward Office, Karve Road, Pune 411004',
      lat: 18.5158,
      lng: 73.8415,
      schedule: 'Every Saturday, 8:00 AM – 12:30 PM',
      date: '2026-10-18T08:00:00.000Z',
      duration: '4 Weeks',
      hours: 18,
      capacity: 30,
      appliedCount: 14,
      status: 'open',
      category: 'Environment',
      format: 'weekly',
      timingDetails: 'Every Saturday, 08:00 AM – 12:30 PM IST (Weekly Cohort)',
      image: '/src/assets/images/opp_river_cleanup_1790697042279.jpg'
    },
    {
      id: 'opp_pune_resq_animal',
      orgId: 'org_pune_animal',
      title: 'RESQ Wildlife & Domestic Animal Sanctuary Volunteering',
      description: 'Hands-on animal care and shelter enrichment at RESQ Centre Bavdhan! College volunteers assist veterinary staff with stray dog grooming, kennel maintenance, orphaned puppy bottle-feeding, and public animal adoption counseling.',
      skills: 'Animal Care, Volunteer Management, Public Outreach, Empathy & Care',
      city: 'Pune',
      address: 'RESQ Wildlife Trauma Centre, Paud Road, Bavdhan, Pune 411021',
      lat: 18.5134,
      lng: 73.7699,
      schedule: 'Every Saturday & Sunday, 8:30 AM – 1:00 PM',
      date: '2026-10-24T08:30:00.000Z',
      duration: '6 Weeks',
      hours: 24,
      capacity: 25,
      appliedCount: 12,
      status: 'open',
      category: 'Animal Welfare',
      format: 'weekly',
      timingDetails: 'Every Saturday & Sunday, 08:30 AM – 01:00 PM IST (Weekly Cohort)',
      image: '/src/assets/images/opp_senior_care_1790696996205.jpg'
    },
    {
      id: 'opp_pune_deepstambha_stem',
      orgId: 'org_pune_edu',
      title: 'COEP-Deepstambha Weekend Robotics & Coding Clinic',
      description: 'College squads from COEP and Pune universities conduct hands-on Scratch coding, Arduino demonstrations, and fun science experiments for underprivileged 7th–9th graders at PMC Vidyaniketan School.',
      skills: 'Teaching, Python, Robotics, Public Speaking',
      city: 'Pune',
      address: 'PMC Vidyaniketan Model School, Shivajinagar, Pune 411005',
      lat: 18.5314,
      lng: 73.8446,
      schedule: 'Every Sunday, 10:00 AM – 2:00 PM',
      date: '2026-11-01T10:00:00.000Z',
      duration: '4 Weeks',
      hours: 16,
      capacity: 20,
      appliedCount: 15,
      status: 'open',
      category: 'Education',
      format: 'weekly',
      timingDetails: 'Every Sunday, 10:00 AM – 02:00 PM IST (Weekly Cohort)',
      image: '/src/assets/images/srm_stem_robotics_1790532269549.jpg'
    },
    {
      id: 'opp_pune_democracy_campaign',
      orgId: 'org_pune_civic',
      title: 'Pune Youth Vote: Campus Voter Enrolment & Civic Rights Sprint',
      description: 'Host youth voter helpdesks at colleges across Pune (COEP, SPPU, Fergusson). Assist first-time voters with online Form 6 enrolment and stage street theater on municipal accountability.',
      skills: 'Public Speaking, Community Mobilization, Event Planning, Social Media',
      city: 'Pune',
      address: 'Savitribai Phule Pune University Campus Enclave, Ganeshkhind, Pune 411007',
      lat: 18.5529,
      lng: 73.8260,
      schedule: '3-Week Campaign: Tue/Thu campus booths + Sat rally',
      date: '2026-10-22T09:00:00.000Z',
      duration: '3 Weeks',
      hours: 18,
      capacity: 35,
      appliedCount: 16,
      status: 'open',
      category: 'Civic & Democracy',
      format: 'campaign',
      timingDetails: '3-Week Campaign: Tue/Thu 4-6 PM + Sat 9 AM-1 PM',
      image: '/src/assets/images/opp_civic_debate_1790697345173.jpg'
    },
    {
      id: 'opp_pune_sanjeevan_health',
      orgId: 'org_pune_health',
      title: 'Katraj Urban Slum Preventive Health Screening Camp',
      description: 'Single-day medical camp screening 500+ residents for hypertension, blood sugar, and pediatric vitals. Student volunteers coordinate patient registration and medicine packaging.',
      skills: 'First Aid, Lab Research, Public Health, Volunteer Management',
      city: 'Pune',
      address: 'Community Hall, Katraj Kondhwa Road, Pune 411046',
      lat: 18.4529,
      lng: 73.8652,
      schedule: 'Single Day Blitz: Sunday, 8:00 AM – 4:00 PM',
      date: '2026-10-25T08:00:00.000Z',
      duration: '1 Day',
      hours: 8,
      capacity: 30,
      appliedCount: 18,
      status: 'open',
      category: 'Healthcare',
      format: 'one_day_drive',
      timingDetails: 'Single Day Medical Camp: Sunday, 08:00 AM – 04:00 PM IST (8 hrs)',
      image: '/src/assets/images/srm_health_camp_1790532283536.jpg'
    },

    // --- KOLKATA OPPORTUNITIES ---
    {
      id: 'opp_kolkata_hooghly_cleanup',
      orgId: 'org_kolkata_env',
      title: 'Hooghly Riverfront Ghat Restoration & Biodiversity Audit',
      description: 'Dawn environmental action along Princep Ghat and Babughat! Student squads from Jadavpur University and Presidency collect non-biodegradable debris and log water quality metrics.',
      skills: 'Environmental Action, Logistics, Surveying, Data Analysis',
      city: 'Kolkata',
      address: 'Princep Ghat Promenade, Strand Road, Kolkata 700021',
      lat: 22.5562,
      lng: 88.3308,
      schedule: 'Single Day Drive: Saturday, 6:30 AM – 11:30 AM',
      date: '2026-10-24T06:30:00.000Z',
      duration: '1 Day',
      hours: 6,
      capacity: 45,
      appliedCount: 20,
      status: 'open',
      category: 'Environment',
      format: 'one_day_drive',
      timingDetails: 'Single Day Drive: Saturday, 06:30 AM – 11:30 AM IST (5 hrs)',
      image: '/src/assets/images/opp_lake_cleanup_1790697306799.jpg'
    },
    {
      id: 'opp_kolkata_animal_shelter',
      orgId: 'org_kolkata_animal',
      title: 'South Kolkata Animal Rescue & Street Feeding Drive',
      description: 'Join Kolkata veterinary teams to assist injured street dogs and cats, manage vaccination camps, and carry out morning nutrition rounds around Tollygunge and Jadavpur.',
      skills: 'Animal Care, Volunteer Management, Empathy & Care',
      city: 'Kolkata',
      address: 'Calcutta Animal Care Centre, Raja SC Mullick Road, Jadavpur, Kolkata 700032',
      lat: 22.4988,
      lng: 88.3712,
      schedule: 'Every Saturday & Sunday, 8:00 AM – 11:30 AM',
      date: '2026-10-31T08:00:00.000Z',
      duration: '4 Weeks',
      hours: 20,
      capacity: 25,
      appliedCount: 11,
      status: 'open',
      category: 'Animal Welfare',
      format: 'weekly',
      timingDetails: 'Every Saturday & Sunday, 08:00 AM – 11:30 AM IST (Weekly Cohort)',
      image: '/src/assets/images/opp_vet_mobile_1790697217814.jpg'
    },
    {
      id: 'opp_kolkata_bikash_literacy',
      orgId: 'org_kolkata_edu',
      title: 'Sealdah Railway Sidings Children Community Library & Learning Lab',
      description: 'Set up vibrant reading circles, basic English literacy, and arithmetic games for 200 children living in informal settlements near Sealdah station.',
      skills: 'Teaching, Content Writing, Event Planning, Community Mobilization',
      city: 'Kolkata',
      address: 'Bikash Learning Centre, Acharya Prafulla Chandra Road, Sealdah, Kolkata 700009',
      lat: 22.5697,
      lng: 88.3713,
      schedule: 'Every Friday & Saturday, 10:00 AM – 2:00 PM',
      date: '2026-11-06T10:00:00.000Z',
      duration: '3 Weeks',
      hours: 18,
      capacity: 30,
      appliedCount: 14,
      status: 'open',
      category: 'Education',
      format: 'weekly',
      timingDetails: 'Every Friday & Saturday, 10:00 AM – 02:00 PM IST (Weekly Cohort)',
      image: '/src/assets/images/srm_library_story_1790570169598.jpg'
    },
    {
      id: 'opp_kolkata_rescue_clinic',
      orgId: 'org_kolkata_health',
      title: 'Calcutta Rescue Mobile Street Clinic & Wellness Blitz',
      description: 'Assist doctors and pharmacists in delivering primary health care, vitals screening, and pediatric nutrition for urban street dwellers.',
      skills: 'First Aid, Public Health, Lab Research, Logistics',
      city: 'Kolkata',
      address: 'Calcutta Rescue Clinic Hub, Park Circus 7-Point Crossing, Kolkata 700017',
      lat: 22.5448,
      lng: 88.3697,
      schedule: 'Saturday Clinic Camp, 9:00 AM – 3:30 PM',
      date: '2026-11-14T09:00:00.000Z',
      duration: '2 Days',
      hours: 12,
      capacity: 25,
      appliedCount: 16,
      status: 'open',
      category: 'Healthcare',
      format: 'one_day_drive',
      timingDetails: 'Medical Camp: Saturday, 09:00 AM – 03:30 PM IST (6.5 hrs)',
      image: '/src/assets/images/opp_vision_clinic_1790570208128.jpg'
    },
    {
      id: 'opp_kolkata_democracy_campaign',
      orgId: 'org_kolkata_civic',
      title: 'Bengal Youth Vote & Civic Participation Campaign',
      description: 'Lead non-partisan voter enrollment kiosks and host debates across university clusters (Jadavpur, Presidency, Calcutta University) ahead of elections.',
      skills: 'Public Speaking, Social Media, Event Planning, Civic Literacy',
      city: 'Kolkata',
      address: 'University Square Enclave, College Street, Kolkata 700073',
      lat: 22.5744,
      lng: 88.3629,
      schedule: '3-Week Campaign Sprint: Wed/Fri campus booths + Sat rallies',
      date: '2026-10-28T10:00:00.000Z',
      duration: '3 Weeks',
      hours: 18,
      capacity: 35,
      appliedCount: 15,
      status: 'open',
      category: 'Civic & Democracy',
      format: 'campaign',
      timingDetails: '3-Week Campaign: Wed/Fri booths + Sat public rallies',
      image: '/src/assets/images/srm_student_lead_1790532310998.jpg'
    },

    // --- AHMEDABAD OPPORTUNITIES ---
    {
      id: 'opp_ahmedabad_sabarmati_eco',
      orgId: 'org_ahmedabad_env',
      title: 'Sabarmati Riverfront Biodiversity & Urban Miyawaki Forest Drive',
      description: 'Plant 1,200 native trees along Sabarmati riverfront promenade! Volunteers work in college squads managing soil beds, mulch preparation, and geotagging.',
      skills: 'Environmental Action, Logistics, Surveying, Volunteer Management',
      city: 'Ahmedabad',
      address: 'Sabarmati Riverfront Biodiversity Park, Usmanpura, Ahmedabad 380013',
      lat: 23.0450,
      lng: 72.5714,
      schedule: 'Single Day Drive: Sunday, 6:30 AM – 11:30 AM',
      date: '2026-10-25T06:30:00.000Z',
      duration: '1 Day',
      hours: 6,
      capacity: 50,
      appliedCount: 22,
      status: 'open',
      category: 'Environment',
      format: 'one_day_drive',
      timingDetails: 'Single Day Drive: Sunday, 06:30 AM – 11:30 AM IST (5 hrs)',
      image: '/src/assets/images/opp_heritage_care_1790697125159.jpg'
    },
    {
      id: 'opp_ahmedabad_jivdaya_animal',
      orgId: 'org_ahmedabad_animal',
      title: 'Jivdaya Animal Hospital & Avian Care Volunteering',
      description: 'Support doctors at Gujarat’s largest non-profit animal hospital caring for injured pigeons, street dogs, and native wildlife. Volunteers assist with feeding, bandaging, and records.',
      skills: 'Animal Care, Empathy & Care, Volunteer Management',
      city: 'Ahmedabad',
      address: 'Jivdaya Hospital, Ahmedabad Panjrapole Campus, Ambawadi, Ahmedabad 380015',
      lat: 23.0189,
      lng: 72.5422,
      schedule: 'Every Saturday & Sunday, 9:00 AM – 1:00 PM',
      date: '2026-10-31T09:00:00.000Z',
      duration: '4 Weeks',
      hours: 20,
      capacity: 25,
      appliedCount: 13,
      status: 'open',
      category: 'Animal Welfare',
      format: 'weekly',
      timingDetails: 'Every Saturday & Sunday, 09:00 AM – 01:00 PM IST (Weekly Cohort)',
      image: '/src/assets/images/opp_food_relief_1790697025433.jpg'
    },
    {
      id: 'opp_ahmedabad_eklavya_stem',
      orgId: 'org_ahmedabad_edu',
      title: 'Eklavya Hands-On Science & Coding Mentors for Municipal Schools',
      description: 'Engage 6th–8th graders with simple optics, water filtration models, and block coding. Perfect for engineering and science students from IIT Gandhinagar and Gujarat University.',
      skills: 'Teaching, STEM Mentorship, Python, Public Speaking',
      city: 'Ahmedabad',
      address: 'Municipal School No. 12, Ashram Road, Navrangpura, Ahmedabad 380009',
      lat: 23.0368,
      lng: 72.5614,
      schedule: 'Every Saturday, 10:00 AM – 2:00 PM',
      date: '2026-11-07T10:00:00.000Z',
      duration: '4 Weeks',
      hours: 16,
      capacity: 25,
      appliedCount: 14,
      status: 'open',
      category: 'Education',
      format: 'weekly',
      timingDetails: 'Every Saturday, 10:00 AM – 02:00 PM IST (Weekly Cohort)',
      image: '/src/assets/images/featured_digital_literacy_1790530845015.jpg'
    },
    {
      id: 'opp_ahmedabad_sewa_health',
      orgId: 'org_ahmedabad_health',
      title: 'SEWA Peri-Urban Community Nutrition & Health Clinic',
      description: 'Collaborate with SEWA community health workers to screen women and children for anemia and malnutrition, distributing fortified nutrition packs in eastern Ahmedabad.',
      skills: 'First Aid, Public Health, Logistics, Community Mobilization',
      city: 'Ahmedabad',
      address: 'SEWA Community Center, Bapunagar Industrial Cluster, Ahmedabad 380024',
      lat: 23.0412,
      lng: 72.6289,
      schedule: 'Saturday Clinic, 8:30 AM – 2:30 PM',
      date: '2026-11-14T08:30:00.000Z',
      duration: '1 Weekend',
      hours: 12,
      capacity: 25,
      appliedCount: 12,
      status: 'open',
      category: 'Healthcare',
      format: 'one_day_drive',
      timingDetails: 'Health & Nutrition Camp: Saturday, 08:30 AM – 02:30 PM IST (6 hrs)',
      image: '/src/assets/images/opp_artisan_fair_1790697254888.jpg'
    },
    {
      id: 'opp_ahmedabad_civic_democracy',
      orgId: 'org_ahmedabad_civic',
      title: 'Janpath Youth Electoral Enrolment & Rights Campaign',
      description: 'Coordinate voter literacy helpdesks across college campuses in Ahmedabad and Gandhinagar. Educate students on Form 6 and voting rights.',
      skills: 'Public Speaking, Event Planning, Community Mobilization, Social Media',
      city: 'Ahmedabad',
      address: 'Gujarat University Convention Hall & Campus, Navrangpura, Ahmedabad 380009',
      lat: 23.0360,
      lng: 72.5460,
      schedule: '3-Week Campaign: Tue/Thu campus helpdesks + Sat street plays',
      date: '2026-10-20T10:00:00.000Z',
      duration: '3 Weeks',
      hours: 18,
      capacity: 35,
      appliedCount: 16,
      status: 'open',
      category: 'Civic & Democracy',
      format: 'campaign',
      timingDetails: '3-Week Campaign: Tue/Thu helpdesks + Sat street plays',
      image: '/src/assets/images/hero_student_outreach_1790530832259.jpg'
    },

    // --- COIMBATORE OPPORTUNITIES ---
    {
      id: 'opp_coimbatore_siruthuli_lake',
      orgId: 'org_coimbatore_env',
      title: 'Siruthuli Valankulam Lake Rejuvenation & Desilting Blitz',
      description: 'Mobilize 200+ engineering and arts students around Valankulam Lake to clear shoreline debris, plant vetiver grass to prevent soil erosion, and test dissolved oxygen levels.',
      skills: 'Environmental Action, Logistics, Surveying, Data Analysis',
      city: 'Coimbatore',
      address: 'Valankulam Lake Promenade, Sungam Bypass Road, Ramanathapuram, Coimbatore 641045',
      lat: 10.9984,
      lng: 76.9745,
      schedule: 'Single Day Drive: Saturday, 6:30 AM – 11:30 AM',
      date: '2026-10-24T06:30:00.000Z',
      duration: '1 Day',
      hours: 6,
      capacity: 50,
      appliedCount: 24,
      status: 'open',
      category: 'Environment',
      format: 'one_day_drive',
      timingDetails: 'Single Day Drive: Saturday, 06:30 AM – 11:30 AM IST (5 hrs)',
      image: '/src/assets/images/opp_lake_restoration_1790570182484.jpg'
    },
    {
      id: 'opp_coimbatore_has_animal',
      orgId: 'org_coimbatore_animal',
      title: 'HAS Coimbatore Animal Sanctuary Care & Rehabilitation',
      description: 'Work alongside veterinary nurses at HAS India sanctuary caring for rescued dogs, cats, and equines. Volunteers assist with puppy socialization, daily feeding, and adoption drives.',
      skills: 'Animal Care, Empathy & Care, Volunteer Management',
      city: 'Coimbatore',
      address: 'Humane Animal Society Centre, Seeranaickenpalayam, Coimbatore 641007',
      lat: 11.0125,
      lng: 76.9245,
      schedule: 'Every Saturday & Sunday, 8:30 AM – 12:30 PM',
      date: '2026-10-31T08:30:00.000Z',
      duration: '4 Weeks',
      hours: 20,
      capacity: 25,
      appliedCount: 15,
      status: 'open',
      category: 'Animal Welfare',
      format: 'weekly',
      timingDetails: 'Every Saturday & Sunday, 08:30 AM – 12:30 PM IST (Weekly Cohort)',
      image: '/src/assets/images/opp_pollinator_bio_1790697267542.jpg'
    },
    {
      id: 'opp_coimbatore_shanti_edu',
      orgId: 'org_coimbatore_edu',
      title: 'Shanti Ashram Rural Children Reading & Digital Skills Camp',
      description: 'Volunteer teams from PSG Tech and Amrita University run interactive science, storytelling, and digital tablet learning sessions for rural children in Perur village.',
      skills: 'Teaching, Digital Literacy, Public Speaking, Content Writing',
      city: 'Coimbatore',
      address: 'Shanti Ashram Rural Center, Perur Main Road, Coimbatore 641010',
      lat: 10.9740,
      lng: 76.9150,
      schedule: 'Every Saturday, 10:00 AM – 2:00 PM',
      date: '2026-11-07T10:00:00.000Z',
      duration: '4 Weeks',
      hours: 16,
      capacity: 30,
      appliedCount: 18,
      status: 'open',
      category: 'Education',
      format: 'weekly',
      timingDetails: 'Every Saturday, 10:00 AM – 02:00 PM IST (Weekly Cohort)',
      image: '/src/assets/images/opp_sports_camp_1790697103873.jpg'
    },
    {
      id: 'opp_coimbatore_mobile_health',
      orgId: 'org_coimbatore_health',
      title: 'Kovai Foothills Mobile Health & Vision Screening Camp',
      description: 'Join community doctors to conduct non-invasive diabetes screening and refractive eye tests for 400 rural agricultural workers in Thondamuthur.',
      skills: 'First Aid, Public Health, Logistics, Surveying',
      city: 'Coimbatore',
      address: 'Panchayat Community Hall, Thondamuthur, Coimbatore 641109',
      lat: 10.9850,
      lng: 76.8450,
      schedule: 'Single Day Medical Camp: Sunday, 8:00 AM – 3:30 PM',
      date: '2026-11-15T08:00:00.000Z',
      duration: '1 Day',
      hours: 8,
      capacity: 25,
      appliedCount: 14,
      status: 'open',
      category: 'Healthcare',
      format: 'one_day_drive',
      timingDetails: 'Single Day Camp: Sunday, 08:00 AM – 03:30 PM IST (7.5 hrs)',
      image: '/src/assets/images/opp_solar_tech_1790697235738.jpg'
    },
    {
      id: 'opp_coimbatore_civic_democracy',
      orgId: 'org_coimbatore_civic',
      title: 'Kongu Youth Vote: Collegiate Electoral & Civic Literacy Sprint',
      description: 'Host youth voter helpdesks at colleges across Coimbatore. Educate students on Form 6 and conduct youth parliament simulations on municipal civic rights.',
      skills: 'Public Speaking, Event Planning, Community Mobilization, Social Media',
      city: 'Coimbatore',
      address: 'PSG College of Technology & Avinashi Road Campus, Peelamedu, Coimbatore 641004',
      lat: 11.0245,
      lng: 77.0028,
      schedule: '3-Week Campaign: Tue/Thu booths + Sat rally',
      date: '2026-10-21T09:30:00.000Z',
      duration: '3 Weeks',
      hours: 18,
      capacity: 35,
      appliedCount: 15,
      status: 'open',
      category: 'Civic & Democracy',
      format: 'campaign',
      timingDetails: '3-Week Campaign: Tue/Thu 4-6 PM + Sat 9 AM-1 PM',
      image: '/src/assets/images/campus_team_impact_1790530881758.jpg'
    },

    // --- VELLORE OPPORTUNITIES ---
    {
      id: 'opp_vellore_rural_literacy',
      orgId: 'org_vellore_rural',
      title: 'VIT Katpadi Rural Digital Literacy & Night School Mentorship',
      description: 'Collaborate with VIT Vellore student chapters to power evening smart classes, computer training, and scholarship applications for 150 Katpadi school students.',
      skills: 'Digital Literacy, Teaching, Web Development, Public Speaking',
      city: 'Vellore',
      address: 'Panchayat Union School, Katpadi Railway Station Road, Vellore 632007',
      lat: 12.9750,
      lng: 79.1410,
      schedule: 'Every Saturday & Sunday, 9:30 AM – 1:30 PM',
      date: '2026-10-18T09:30:00.000Z',
      duration: '4 Weeks',
      hours: 20,
      capacity: 30,
      appliedCount: 18,
      status: 'open',
      category: 'Education',
      format: 'weekly',
      timingDetails: 'Every Saturday & Sunday, 09:30 AM – 01:30 PM IST (Weekly Cohort)',
      image: '/src/assets/images/opp_child_support_1790697360371.jpg'
    },
    {
      id: 'opp_vellore_cmc_health',
      orgId: 'org_vellore_health',
      title: 'CMC RUHSA Rural Preventive Health & Nutrition Camp',
      description: 'Partner with CMC Vellore community medicine teams to conduct vitals screening, anemia checks, and maternal health counseling across KV Kuppam rural hamlets.',
      skills: 'First Aid, Public Health, Lab Research, Volunteer Management',
      city: 'Vellore',
      address: 'CMC RUHSA Community Health Centre, KV Kuppam Block, Vellore 632201',
      lat: 12.9810,
      lng: 79.0340,
      schedule: 'Single Day Medical Camp: Saturday, 8:00 AM – 4:00 PM',
      date: '2026-10-24T08:00:00.000Z',
      duration: '1 Day',
      hours: 8,
      capacity: 30,
      appliedCount: 22,
      status: 'open',
      category: 'Healthcare',
      format: 'one_day_drive',
      timingDetails: 'Single Day Medical Camp: Saturday, 08:00 AM – 04:00 PM IST (8 hrs)',
      image: '/src/assets/images/opp_eye_clinic_1790697283229.jpg'
    },
    {
      id: 'opp_vellore_palar_env',
      orgId: 'org_vellore_env',
      title: 'Palar Riverbed Green Belt Native Tree Planting Drive',
      description: 'Plant 1,000 indigenous trees along the Palar riverbank to curb sand erosion and restore the groundwater table in Katpadi and Virinjipuram.',
      skills: 'Environmental Action, Logistics, Surveying, Volunteer Management',
      city: 'Vellore',
      address: 'Palar River Green Belt, Old Katpadi Bridge Road, Vellore 632006',
      lat: 12.9420,
      lng: 79.1350,
      schedule: 'Single Day Blitz: Sunday, 6:30 AM – 11:30 AM',
      date: '2026-11-01T06:30:00.000Z',
      duration: '1 Day',
      hours: 6,
      capacity: 40,
      appliedCount: 16,
      status: 'open',
      category: 'Environment',
      format: 'one_day_drive',
      timingDetails: 'Single Day Drive: Sunday, 06:30 AM – 11:30 AM IST (5 hrs)',
      image: '/src/assets/images/srm_tree_planting_1790532298221.jpg'
    },
    {
      id: 'opp_vellore_paws_animal',
      orgId: 'org_vellore_animal',
      title: 'Vellore Fort Perimeter Stray Animal Rescue & Feeding Care',
      description: 'Join veterinary helpers for weekend stray dog feeding rounds, anti-rabies vaccination tagging, and adoption awareness near Vellore Fort and Katpadi.',
      skills: 'Animal Care, Empathy & Care, Volunteer Management',
      city: 'Vellore',
      address: 'Vellore Animal Shelter & Clinic, Fort Round Road, Vellore 632004',
      lat: 12.9230,
      lng: 79.1320,
      schedule: 'Every Saturday, 8:00 AM – 11:30 AM',
      date: '2026-11-07T08:00:00.000Z',
      duration: '4 Weeks',
      hours: 16,
      capacity: 20,
      appliedCount: 10,
      status: 'open',
      category: 'Animal Welfare',
      format: 'weekly',
      timingDetails: 'Every Saturday, 08:00 AM – 11:30 AM IST (Weekly Cohort)',
      image: '/src/assets/images/story_aarav_vit_1790530857035.jpg'
    },
    {
      id: 'opp_vellore_civic_democracy',
      orgId: 'org_vellore_civic',
      title: 'Vellore First-Time Voter Registration & Democracy Helpdesk',
      description: 'Set up campus kiosks across VIT Vellore and Katpadi arts colleges to register over 1,000 eligible first-time student voters on the National Voter Services Portal.',
      skills: 'Public Speaking, Event Planning, Community Mobilization, Civic Literacy',
      city: 'Vellore',
      address: 'VIT University Campus Gate 1 & Katpadi Enclave, Vellore 632014',
      lat: 12.9698,
      lng: 79.1559,
      schedule: '3-Week Campaign: Mon/Wed campus booths + Sat rallies',
      date: '2026-10-26T09:00:00.000Z',
      duration: '3 Weeks',
      hours: 18,
      capacity: 30,
      appliedCount: 15,
      status: 'open',
      category: 'Civic & Democracy',
      format: 'campaign',
      timingDetails: '3-Week Campaign: Mon/Wed booths + Sat rallies',
      image: '/src/assets/images/story_meera_chennai_1790530867787.jpg'
    },

    // --- HYDERABAD WEEKLY OPPORTUNITY ---
    {
      id: 'opp_hyd_stem_coding',
      orgId: 'org_youthforseva',
      title: 'Hyderabad Cyberabad Weekend Girls in STEM & Coding Clinic',
      description: 'Every Saturday collegiate mentor squads teach web fundamentals, Python, and digital logic to high school girls from underprivileged communities in Gachibowli.',
      skills: 'Teaching, Python, Web Development, STEM Mentorship',
      city: 'Hyderabad',
      address: 'Youth for Seva Learning Hub, Gachibowli Telecom Nagar, Hyderabad 500032',
      lat: 17.4401,
      lng: 78.3489,
      schedule: 'Every Saturday, 9:30 AM – 1:30 PM',
      date: '2026-10-24T09:30:00.000Z',
      duration: '4 Weeks',
      hours: 16,
      capacity: 25,
      appliedCount: 14,
      status: 'open',
      category: 'Education',
      format: 'weekly',
      timingDetails: 'Every Saturday, 09:30 AM – 01:30 PM IST (Weekly Cohort)',
      image: '/src/assets/images/opp_mobile_library_1790697323615.jpg'
    },

    // --- MUMBAI WEEKLY OPPORTUNITY ---
    {
      id: 'opp_mumbai_inclusive_art',
      orgId: 'org_cleancity',
      title: 'Bandra Inclusive Arts & Creative Expression Circle',
      description: 'Weekly Sunday community sessions conducting pottery, clay sculpting, and watercolor workshops for children with neurodivergent needs and elder companions.',
      skills: 'Teaching, Empathy & Care, Event Planning, Public Speaking',
      city: 'Mumbai',
      address: 'Bandra Bandstand Community Hall, BJ Road, Bandra West, Mumbai 400050',
      lat: 19.0434,
      lng: 72.8197,
      schedule: 'Every Sunday, 10:00 AM – 1:30 PM',
      date: '2026-10-25T10:00:00.000Z',
      duration: '4 Weeks',
      hours: 14,
      capacity: 20,
      appliedCount: 11,
      status: 'open',
      category: 'Community Action',
      format: 'weekly',
      timingDetails: 'Every Sunday, 10:00 AM – 01:30 PM IST (Weekly Cohort)',
      image: '/src/assets/images/opp_inclusive_art_1790697088869.jpg'
    }
  ];


  // Insert or replace all opportunities
  const insertOpp = db.prepare(`
    INSERT OR REPLACE INTO opportunities (
      id, org_id, title, description, skills_needed, city, address, latitude, longitude,
      schedule, date, duration, hours, capacity, applied_count, status, category,
      activity_format, timing_details, image, created_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  opportunitiesToSeed.forEach((o) => {
    insertOpp.run(
      o.id,
      o.orgId,
      o.title,
      o.description,
      o.skills,
      o.city,
      o.address,
      o.lat,
      o.lng,
      o.schedule,
      o.date,
      o.duration,
      o.hours,
      o.capacity,
      o.appliedCount,
      o.status,
      o.category,
      o.format,
      o.timingDetails,
      o.image,
      '2026-08-15T08:00:00.000Z'
    );
  });

  // 5. Seed Collegiate Squads & Leaderboard Data
  // Create squads for new opportunities and assign completed hours for leaderboard
  const teamsToSeed = [
    // SRM Teams (Chennai)
    { id: 'team_srm_digital', oppId: 'opp_digital_literacy', college: 'SRM Kattankulathur (KTR)', city: 'Chennai', name: 'SRM Kattankulathur Squad' },
    { id: 'team_srm_marina', oppId: 'opp_srm_marina_cleanup', college: 'SRM Kattankulathur (KTR)', city: 'Chennai', name: 'SRM Green Warriors Squad' },
    { id: 'team_srm_health', oppId: 'opp_community_health_camp', college: 'SRM Kattankulathur (KTR)', city: 'Chennai', name: 'SRM Medical Outreach Squad' },
    { id: 'team_srm_nutrition', oppId: 'opp_community_nutrition', college: 'SRM Kattankulathur (KTR)', city: 'Chennai', name: 'SRM Annadanam Squad' },
    { id: 'team_srm_vision', oppId: 'opp_school_vision_clinic', college: 'SRM Kattankulathur (KTR)', city: 'Chennai', name: 'SRM Vision Squad' },
    { id: 'team_srm_animal', oppId: 'opp_animal_shelter', college: 'SRM Kattankulathur (KTR)', city: 'Chennai', name: 'SRM Paws Care Squad' },

    // VIT Vellore Teams
    { id: 'team_vit_digital', oppId: 'opp_digital_literacy', college: 'VIT Vellore', city: 'Vellore', name: 'VIT Vellore Squad' },
    { id: 'team_vit_literacy', oppId: 'opp_vellore_rural_literacy', college: 'VIT Vellore', city: 'Vellore', name: 'VIT Katpadi Innovators' },
    { id: 'team_vit_palar', oppId: 'opp_vellore_palar_env', college: 'VIT Vellore', city: 'Vellore', name: 'VIT Palar Eco Squad' },
    { id: 'team_vit_paws', oppId: 'opp_vellore_paws_animal', college: 'VIT Vellore', city: 'Vellore', name: 'VIT Animal Welfare Squad' },
    { id: 'team_vit_civic', oppId: 'opp_vellore_civic_democracy', college: 'VIT Vellore', city: 'Vellore', name: 'VIT Youth Democracy Club' },

    // IIT Madras Teams
    { id: 'team_iitm_digital', oppId: 'opp_digital_literacy', college: 'IIT Madras', city: 'Chennai', name: 'IIT Madras Squad' },
    { id: 'team_iitm_coastal', oppId: 'opp_coastal_waste_audit', college: 'IIT Madras', city: 'Chennai', name: 'IITM Ocean Protectors' },
    { id: 'team_iitm_marina', oppId: 'opp_srm_marina_cleanup', college: 'IIT Madras', city: 'Chennai', name: 'IITM Coastal Squad' },

    // DU Teams (Delhi)
    { id: 'team_du_yamuna', oppId: 'opp_yamuna_afforestation', college: 'University of Delhi', city: 'Delhi', name: 'Delhi University Squad' },
    { id: 'team_du_democracy', oppId: 'opp_election_awareness', college: 'University of Delhi', city: 'Delhi', name: 'DU Electoral Club' },
    { id: 'team_du_ridge', oppId: 'opp_urban_biodiversity_delhi', college: 'University of Delhi', city: 'Delhi', name: 'DU Ridge Explorers' },

    // IIT Delhi Teams
    { id: 'team_iitd_yamuna', oppId: 'opp_yamuna_afforestation', college: 'IIT Delhi', city: 'Delhi', name: 'IIT Delhi Squad' },
    { id: 'team_iitd_solar', oppId: 'opp_rural_solar_survey', college: 'IIT Delhi', city: 'Delhi', name: 'IITD Clean Energy Squad' },

    // COEP Pune Teams
    { id: 'team_coep_waste', oppId: 'opp_pune_swach_waste', college: 'COEP Technological University', city: 'Pune', name: 'COEP Swach Warriors' },
    { id: 'team_coep_robotics', oppId: 'opp_pune_deepstambha_stem', college: 'COEP Technological University', city: 'Pune', name: 'COEP RoboMentors' },
    { id: 'team_coep_resq', oppId: 'opp_pune_resq_animal', college: 'COEP Technological University', city: 'Pune', name: 'COEP Paws Rescue' },

    // Jadavpur University Teams (Kolkata)
    { id: 'team_ju_hooghly', oppId: 'opp_kolkata_hooghly_cleanup', college: 'Jadavpur University', city: 'Kolkata', name: 'Jadavpur River Guardians' },
    { id: 'team_ju_bikash', oppId: 'opp_kolkata_bikash_literacy', college: 'Jadavpur University', city: 'Kolkata', name: 'Jadavpur Sealdah Tutors' },

    // IIT Gandhinagar Teams (Ahmedabad)
    { id: 'team_iitgn_sabarmati', oppId: 'opp_ahmedabad_sabarmati_eco', college: 'IIT Gandhinagar', city: 'Ahmedabad', name: 'IITGN Eco Knights' },
    { id: 'team_iitgn_jivdaya', oppId: 'opp_ahmedabad_jivdaya_animal', college: 'IIT Gandhinagar', city: 'Ahmedabad', name: 'IITGN Animal Compassion' },

    // PSG Tech Teams (Coimbatore)
    { id: 'team_psg_lake', oppId: 'opp_coimbatore_siruthuli_lake', college: 'PSG College of Technology', city: 'Coimbatore', name: 'PSG Tech Siruthuli Squad' },
    { id: 'team_psg_has', oppId: 'opp_coimbatore_has_animal', college: 'PSG College of Technology', city: 'Coimbatore', name: 'PSG Animal Welfare Wing' }
  ];

  const insertTeam = db.prepare(`
    INSERT OR REPLACE INTO teams (id, opportunity_id, college, city, team_name, created_at)
    VALUES (?, ?, ?, ?, ?, ?)
  `);

  teamsToSeed.forEach((t) => {
    insertTeam.run(t.id, t.oppId, t.college, t.city, t.name, '2026-08-10T09:00:00.000Z');
  });

  // Assign completed hours and members to squads so that the leaderboard is competitive!
  const squadHourAssignments = [
    { teamId: 'team_srm_digital', hours: 48 },
    { teamId: 'team_srm_marina', hours: 56 },
    { teamId: 'team_srm_health', hours: 64 },
    { teamId: 'team_srm_nutrition', hours: 36 },
    { teamId: 'team_srm_vision', hours: 42 },
    { teamId: 'team_srm_animal', hours: 28 },

    { teamId: 'team_vit_digital', hours: 52 },
    { teamId: 'team_vit_literacy', hours: 44 },
    { teamId: 'team_vit_palar', hours: 38 },
    { teamId: 'team_vit_paws', hours: 32 },

    { teamId: 'team_iitm_digital', hours: 36 },
    { teamId: 'team_iitm_coastal', hours: 40 },
    { teamId: 'team_iitm_marina', hours: 30 },

    { teamId: 'team_du_yamuna', hours: 46 },
    { teamId: 'team_du_democracy', hours: 38 },
    { teamId: 'team_du_ridge', hours: 32 },

    { teamId: 'team_iitd_yamuna', hours: 34 },
    { teamId: 'team_iitd_solar', hours: 40 },

    { teamId: 'team_coep_waste', hours: 42 },
    { teamId: 'team_coep_robotics', hours: 36 },
    { teamId: 'team_coep_resq', hours: 28 },

    { teamId: 'team_ju_hooghly', hours: 38 },
    { teamId: 'team_ju_bikash', hours: 34 },

    { teamId: 'team_iitgn_sabarmati', hours: 36 },
    { teamId: 'team_iitgn_jivdaya', hours: 30 },

    { teamId: 'team_psg_lake', hours: 44 },
    { teamId: 'team_psg_has', hours: 32 }
  ];

  // Update applications with realistic volunteer_hours for team members
  squadHourAssignments.forEach((sa) => {
    try {
      db.prepare(`
        UPDATE applications
        SET volunteer_hours = ?, status = 'completed'
        WHERE team_id = ? AND status = 'applied'
      `).run(Math.round(sa.hours / 3), sa.teamId);
    } catch (e) {
      // ignore
    }
  });

  console.log('Sangam Extended Dataset seeded successfully: 10 cities, all categories, verified NGOs, and leaderboard records.');
}
